services:
  - type: private
    name: typesense
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter # Cambiar a "standard" si necesitas más recursos
    healthCheckPath: /
    disk:
      name: typesense-data
      mountPath: /data
      sizeGB: 1 # Aumentar si planeas indexar grandes volúmenes de datos
    envVars:
      - key: TYPESENSE_API_KEY
        generateValue: true
      - key: TYPESENSE_DATA_DIR
        value: /data
      - key: TYPESENSE_ENABLE_CORS
        value: false # Cambia a "true" si necesitas CORS
